modifications.onclick = () => {
  navigator.clipboard.writeText("Автокликер|Autoclicker|ArmorHotSwap|Clicker|Xray|X-ray|FreeCam|ElytraSwap|MobHealthBar|AutoFish|invMove|AutoTotem|KEYRAN|BotMek|SeedCracker|WalksyOptimizer|SeedCandy|Autorespawn|WalksyCrystalOptimizer|SpeedCrystals|FlashCrystalOptimizer|SwitchTotems|AutoAttack|InventoryTotem|InventoryProfilesNext|AutoBuy|NBTTooltip|ChestESP|ElytraControl|TapeMouse|ClientSidedCrystals|FeverVisual|Featherclient|Bingsautoattack|AutoAim|Bing`sAutoAttack|AutoAim|Nemo'sInventorySorting|Sortitout|LuminarVisual|Shifttap|DarknessVisual|CleanCut|fastPlase|VisibleGhosts|Mytheria|MytheriaVisual|SoupVisual|Soup|Shikaru’sCrystalOptimizer|Shikaru’s|CrystalOptimizer|PlintusVisual|Plintus|ShieldBreaker|Shield|Tweakeroo|AutoCrystalSwitcher|InstantCrystalSwitch|Instant|Automining|FireworkHelper|Firework|DoubleHotbar|Clientcommands|EntityOutliner|Coleslawclient")
  successMasegeModifications.classList.add('active')
  setTimeout(() => successMasegeModifications.classList.remove('active'), 2000)
}
Soft.onclick = () => {
  navigator.clipboard.writeText("Impact|Nursultan|baritone|cabaletta|Matix|R3D|LiquidBounce|Liquid|Bounce|ClownClient|Clown|SquadClient|Squad|Inertiaclient|StressClient|Stress|Neverhook|never|hook|SkillClient|Jessica|Hitbox|Hit|Box|CheatEngine|CheatEngine|Cheat|Wintware|VapeV3|VapeV4|Wurst|WWE|Nodus|Flauncher|Forgehax|kyprakc|Cortex|Cortexclient|Jigsaw|Zamorozka|Infinity|Huzuni|Aristois|SalHack|Ares|AresClient|Meteor|MeteorClient|Sigma|Akrien|External|Externalclient|Norules|Norulesclient|Zenwar|Reverse|Reverseclient|Wild|Wildclient|Deadcode|Aurora|Rage|Pyro|Phobos|GishCode|Future|Konas|Rusherhack|Summit|Celestial|CelestialClient|celka|Wolfram|Eternity|Flux|MixWare|Lambda|Doomsday|Winner|WinnerClient|ClickCrystals|Nursultan|Nursultanclient|WaoHits|NightMare|BoberWare|Expensive|Expensiveclient|Dreampool|Shit|ShitClient|Kami|KamiClient|Exloader|Francium|FranciumClient|Excellent|ExcellentClient|arbyz|arbyzClient|Vegaline|Boze|Bozeclient|Rockstar|Rockstarclient|MoonHack|Rasty|RastyClient|Troxill|TroxillClient|weakson|weaksonclient|Shield|Shieldclient|Avalon|Avalonclient|Fuze|Fuzeclient|Minced|Mincedclient|Syracuse|Prestige|PrestigeClient|Nova|Novaclient|Moon|MoonClient|Budget|BudgetClient|Breeze|BleachHack|Wise|Wissend|Asteria|AsteriaClient|Destroy|DestroyClient|Fluger|FlugerClient|Thunderhack|Delta|DeltaClient|NewLauncher|VenusClient|VenusWare|Venus|ghost|ghostclient|CATLAVAN|CATLAVANClient|sanch|sanchclient|EVERLAST|EVERLASTclient|Vortex|Vortexclient|Luminex|Luminexclient|milexhack|Troxil|TroxilFree|TroxilPremium|Xameleon|XameleonClient|Newcode|NewcodeClient|Haruka|HarukaClient|Fatal|Fatalclient|Neverlose|Neverloseclient|FDP|FDPClient|Monoton|Monotonclient|Augustus|Augustusclient|Domik|Domikclient|DimasikClient|Dimasik|CatleanClient|Catlean|MercuryClient|Mercury|LomtikClient|Lomtik|ReleonClient|Releon|AdvancedKillaura|Crystalcore|tridents-crystalcore|tridents|tridentscrystalcore|XiuClient|Xiu|SystemClient|RadonClient|Radon|MaceCoreClient|MaceCore|AobaClient|Aoba|PatrickClient|Patrick|NewCodeClient|NewCode|MatrixClient|Matrix|MarlowClient|Marlow")
  successMasegeSoft.classList.add('active')
  setTimeout(() => successMasegeSoft.classList.remove('active'), 2000)
}
